### ISSUE TITLE
I need a small

### ISSUE THREAD

**Issue by fahadmh252** [mlnorman/Intro-To-Java-Programming#2]
https://github.com/mlnorman/Intro-To-Java-Programming/blob/1ada4112b72e9245767cccdbe274c10c76d24bbe/Chp6/Exercise_06_03.java#L24
can you please explain for me what is ? and :

**Comment by mlnorman** [comment]
This is called a ternary operator.  Basically and if/else statement in one line.  

? is for you true condition and : is for the false condition.

It is the same as saying:
`if (isPalindrone(numner)) {
  "a"
} else {
  "not a"
}`
